"""empty message

Revision ID: 008bb0545e03
Revises: e61bf4055604
Create Date: 2023-04-11 14:18:13.439676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008bb0545e03'
down_revision = 'e61bf4055604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
