"""empty message

Revision ID: 01333de75443
Revises: 28e37850f66d
Create Date: 2023-04-12 13:20:54.408524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01333de75443'
down_revision = '28e37850f66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
