"""empty message

Revision ID: 636ac1193b9b
Revises: 01333de75443
Create Date: 2023-04-17 15:58:32.331803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636ac1193b9b'
down_revision = '01333de75443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downTimeType', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('downTimeType')

    # ### end Alembic commands ###
